name: smart_menu
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'


dependencies:
  get: ^4.6.5
  flutter_screenutil: ^5.8.4
  google_fonts: ^5.1.0
  lottie: ^2.4.0
  cached_network_image: ^3.2.3
  shimmer: ^3.0.0
  json_annotation: ^4.8.1
  flutter_animated_dialog: ^2.0.1
  image_picker: ^1.0.0
  image_cropper: ^5.0.0
  flutter_switch: ^0.3.2
  dio: ^5.4.0
  http: ^1.2.0
  fluttertoast: ^8.2.2
  path_provider: ^2.0.15
  flutter_image_compress: ^2.0.3
  flutter_cache_manager: ^3.3.1
  qr_flutter: ^4.1.0
  share_plus: ^7.2.1
  screenshot: ^2.1.0
  image_gallery_saver: ^2.0.3
  otp_text_field_v2: ^1.0.3
  intl: ^0.18.1
  loading_icon_button: ^0.0.6
  internet_connection_checker: ^1.0.0+1
  flutter_secure_storage: ^9.0.0
  open_store: ^0.5.0
  package_info_plus: ^4.2.0
  device_info_plus: ^9.1.1
  youtube_player_flutter: ^8.1.2
  flutter_hsvcolor_picker: ^1.5.0
  flutter_stripe: ^9.6.0
  sentry_flutter: ^7.14.0
  showcaseview: ^2.0.3
  pdf: ^3.10.6
  razorpay_flutter: ^1.3.6


  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2

dev_dependencies:
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:

  assets:
    - assets/image/
    - assets/lottie/
    - assets/sounds/
  uses-material-design: true

