const String COMMON_CATEGORY = 'common';
const int MY_SHOP_ID = 10;

//?keys
const String KEY_TOKEN = 'KEY_TOKEN';
const String KEY_SHOP_NAME = 'KEY_SHOP_NAME';
const String KEY_ID = 'KEY_ID';
const String KEY_SHOP_PHONE = 'KEY_SHOP_PHONE';
const String KEY_SHOP_EMAIL = 'KEY_SHOP_EMAIL';
const String KEY_SHOP_PLAN = 'KEY_SHOP_PLAN';
const String KEY_SHOP_EXPAIRY = 'KEY_SHOP_EXPAIRY';
const String KEY_SHOP_STATUS = 'KEY_SHOP_STATUS';

const String KEY_STARTUP_TUTORIAL = 'KEY_STARTUP_TUTORIAL';

const String KEY_QR_SETUP_HOTEL_NAME = 'KEY_QR_SETUP_HOTEL_NAME';
const String KEY_QR_SETUP_SCAN_ME_TXT = 'KEY_QR_SETUP_SCAN_ME_TXT';


const STATIC_TOKEN =
    'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTAsInJvbGUiOiI4OTQzNDc0MzU4IiwiaWF0IjoxNzA4MTEzNjIxfQ.ZAQ4Xg8g28ZgczGy__lzVkA_6nkQ2TXxLG3kKiH3SKg';


const String KEY_SHOWCASE_ADD_FOOD_SCREEN = 'KEY_SHOWCASE_ADD_FOOD_SCREEN';
const String KEY_SHOWCASE_ADD_FOOD_SCREEN_PRICE_NAME_CARD = 'KEY_SHOWCASE_ADD_FOOD_SCREEN_PRICE_TOGGLE';
const String KEY_SHOWCASE_ADD_FOOD_SCREEN_BOTTOM_SHEET = 'KEY_SHOWCASE_ADD_FOOD_SCREEN_BOTTOM_SHEET';
const String KEY_SHOWCASE_FOOD_MENU_SCREEN_ITEM = 'KEY_SHOWCASE_FOOD_MENU_SCREEN_ITEM';
const String KEY_SHOWCASE_OFFER_FOOD_SCREEN_ITEM = 'KEY_SHOWCASE_OFFER_FOOD_SCREEN_ITEM';
const String KEY_SHOWCASE_QR_CODE_DEESIGN_PAGE_CARD = 'KEY_SHOWCASE_QR_CODE_DEESIGN_PAGE_CARD';
const String KEY_SHOWCASE_WEB_MENU_PAGE = 'KEY_SHOWCASE_WEB_MENU_PAGE';
const String KEY_SHOWCASE_HOME_PAGE = 'KEY_SHOWCASE_HOME_PAGE';
