const String COMMON_CATEGORY = 'common';
const int MY_SHOP_ID = 10;

//?keys
const String KEY_TOKEN = 'KEY_TOKEN';
const String KEY_SHOP_NAME = 'KEY_SHOP_NAME';
const String KEY_ID = 'KEY_ID';
const String KEY_SHOP_PHONE = 'KEY_SHOP_PHONE';
const String KEY_SHOP_EMAIL = 'KEY_SHOP_EMAIL';
const String KEY_SHOP_PLAN = 'KEY_SHOP_PLAN';
const String KEY_SHOP_EXPAIRY = 'KEY_SHOP_EXPAIRY';
const String KEY_SHOP_STATUS = 'KEY_SHOP_STATUS';

const String KEY_STARTUP_TUTORIAL = 'KEY_STARTUP_TUTORIAL';

const String KEY_QR_SETUP_HOTEL_NAME = 'KEY_QR_SETUP_HOTEL_NAME';
const String KEY_QR_SETUP_SCAN_ME_TXT = 'KEY_QR_SETUP_SCAN_ME_TXT';


const String STRIPE_LIVE_PUBLISH_KEY = 'pk_live_51OK5KmSJbJA7iybo9e0UyK1QJ6lVcZ5KriM1EeQuVbACKnnbNOQxtflVdxKgm74qPsXSGGu90Oh4L6HWRGCoCnDy00bhCimGbz';
const String STRIPE_TEST_PUBLISH_KEY = 'pk_test_51OK5KmSJbJA7iyboNy8hdbG7RlqQRjNVYoNwJmiSUQOYgmQeFceSE5hYiYkFFSi3NidgJkrCjJDCOdOM5raH6rmz00NGKp23Al';
