enum District {
  ERNAKULAM,
  THRISSUR,
  ALAPPUZHA,
  IDUKKI,
  KANNUR,
  KASARAGOD,
  KOLLAM,
  KOTTAYAM,
  KOZHIKODE,
  MALAPPURAM,
  PALAKKAD,
  PATHANAMTHITTA,
  THIRUVANANTHAPURAM,
  WAYANAD,
  OTHER
}

const Map<District, String> districtDescriptions = {
  District.ERNAKULAM: 'ERNAKULAM',
  District.THRISSUR: 'THRISSUR',
  District.ALAPPUZHA: 'ALAPPUZHA',
  District.IDUKKI: 'IDUKKI',
  District.KANNUR: 'KANNUR',
  District.KASARAGOD: 'KASARAGOD',
  District.KOLLAM: 'KOLLAM',
  District.KOTTAYAM: 'KOTTAYAM',
  District.KOZHIKODE: 'KOZHIKODE',
  District.MALAPPURAM: 'MALAPPURAM',
  District.PALAKKAD: 'PALAKKAD',
  District.PATHANAMTHITTA: 'PATHANAMTHITTA',
  District.THIRUVANANTHAPURAM: 'THIRUVANANTHAPURAM',
  District.WAYANAD: 'WAYANAD',
  District.OTHER: 'OTHER',
};

enum States {
  KERALA,
  ANDHRA_PRADESH,
  ARUNACHAL_PRADESH,
  ASSAM,
  BIHAR,
  CHHATTISGARH,
  GOA,
  GUJARAT,
  HARYANA,
  HIMACHAL_PRADESH,
  JHARKHAND,
  KARNATAKA,
  MADHYA_PRADESH,
  MAHARASHTRA,
  MANIPUR,
  MEGHALAYA,
  MIZORAM,
  NAGALAND,
  ODISHA,
  PUNJAB,
  RAJASTHAN,
  SIKKIM,
  TAMIL_NADU,
  TELANGANA,
  TRIPURA,
  UTTAR_PRADESH,
  UTTARAKHAND,
  WEST_BENGAL,
  ANDAMAN_AND_NICOBAR_ISLANDS,
  CHANDIGARH,
  DADRA_AND_NAGAR_HAVELI_AND_DAMAN_AND_DIU,
  LAKSHADWEEP,
  DELHI,
  PUDUCHERRY,
}




const Map<States, String> stateDescriptions = {
  States.KERALA: 'Kerala',
  States.ANDHRA_PRADESH: 'Andhra Pradesh',
  States.ARUNACHAL_PRADESH: 'Arunachal Pradesh',
  States.ASSAM: 'Assam',
  States.BIHAR: 'Bihar',
  States.CHHATTISGARH: 'Chhattisgarh',
  States.GOA: 'Goa',
  States.GUJARAT: 'Gujarat',
  States.HARYANA: 'Haryana',
  States.HIMACHAL_PRADESH: 'Himachal Pradesh',
  States.JHARKHAND: 'Jharkhand',
  States.KARNATAKA: 'Karnataka',
  States.MADHYA_PRADESH: 'Madhya Pradesh',
  States.MAHARASHTRA: 'Maharashtra',
  States.MANIPUR: 'Manipur',
  States.MEGHALAYA: 'Meghalaya',
  States.MIZORAM: 'Mizoram',
  States.NAGALAND: 'Nagaland',
  States.ODISHA: 'Odisha',
  States.PUNJAB: 'Punjab',
  States.RAJASTHAN: 'Rajasthan',
  States.SIKKIM: 'Sikkim',
  States.TAMIL_NADU: 'Tamil Nadu',
  States.TELANGANA: 'Telangana',
  States.TRIPURA: 'Tripura',
  States.UTTAR_PRADESH: 'Uttar Pradesh',
  States.UTTARAKHAND: 'Uttarakhand',
  States.WEST_BENGAL: 'West Bengal',
  States.CHANDIGARH: 'Chandigarh',
  States.DELHI: 'Delhi',
  States.PUDUCHERRY: 'Puducherry',
};
